# Generated by Django 5.2.4 on 2025-07-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fractory_year',
            new_name='factory_year',
        ),
    ]
